[package]
name = "learn_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "characterType"
path = "src/character_type.rs"

[[bin]]
name = "privimite_types"
path = "src/primitive_types.rs"

[[bin]]
name = "characterType2"
path = "src/character_types_2.rs"

[[bin]]
name = "floatType"
path = "src/floats_type.rs"


[dependencies]
